const stencilsData = [
    {
        number: "1",
        name: "Unicorn",
        image: "./images/1-unicorn.webp",
        url: "https://makerworld.com/en/models/1795890",
    },
    {
        number: "2",
        name: "Eeyore",
        image: "./images/2-eeyore.webp",
        url: "https://makerworld.com/en/models/1797274",
    },
    {
        number: "3",
        name: "Bluey",
        image: "./images/3-bluey.webp",
        url: "https://makerworld.com/en/models/1799035",
    },
    {
        number: "4",
        name: "Harry",
        image: "./images/4-harry.webp",
        url: "https://makerworld.com/en/models/1799051",
    },
    {
        number: "5",
        name: "Ghost Spidey",
        image: "./images/5-ghost-spidey.webp",
        url: "https://makerworld.com/en/models/1801863",
    },
    {
        number: "6",
        name: "Pikachu",
        image: "./images/6-pika.webp",
        url: "https://makerworld.com/en/models/1801865",
    },
    {
        number: "7",
        name: "Shell",
        image: "./images/7-shell.webp",
        url: "https://makerworld.com/en/models/1801870",
    },
    {
        number: "8",
        name: "Olaf",
        image: "./images/8-olaf.webp",
        url: "https://makerworld.com/en/models/1801867",
    },
    {
        number: "9",
        name: "Ralph",
        image: "./images/9-ralph.webp",
        url: "https://makerworld.com/en/models/1801871",
    },
    {
        number: "10",
        name: "Minion",
        image: "./images/10-minion.webp",
        url: "https://makerworld.com/en/models/1801872",
    },
    {
        number: "11",
        name: "Hollow Knight",
        image: "./images/11-hollow-knight.webp",
        url: "https://makerworld.com/en/models/1803287",
    },
    {
        number: "12",
        name: "Groot",
        image: "./images/12-groot.webp",
        url: "https://makerworld.com/en/models/1803825",
    },
    {
        number: "13",
        name: "Link",
        image: "./images/13-link.webp",
        url: "https://makerworld.com/en/models/1804778",
    },
    {
        number: "14",
        name: "Baymax",
        image: "./images/14-baymax.webp",
        url: "https://makerworld.com/en/models/1805113",
    },
    {
        number: "15",
        name: "Carl",
        image: "./images/15-carl.webp",
        url: "https://makerworld.com/en/models/1805165",
    },
    {
        number: "16",
        name: "Calvin",
        image: "./images/16-calvin.webp",
        url: "https://makerworld.com/en/models/1805167",
    },
    {
        number: "17",
        name: "Zelda",
        image: "./images/17-zelda.webp",
        url: "https://makerworld.com/en/models/1806263",
    },
    {
        number: "18",
        name: "Kirby",
        image: "./images/18-kirby.webp",
        url: "https://makerworld.com/en/models/1806730",
    },
    {
        number: "19",
        name: "Pooh",
        image: "./images/19-pooh.webp",
        url: "https://makerworld.com/en/models/1807405",
    },
    {
        number: "20",
        name: "bucees",
        image: "./images/20-bucees.webp",
        url: "https://makerworld.com/en/models/1809609",
    },
    {
        number: "21",
        name: "Tada",
        image: "./images/21-tada.webp",
        url: "https://makerworld.com/en/models/1809610",
    },
    {
        number: "22",
        name: "Dog Man",
        image: "./images/22-dog-man.webp",
        url: "https://makerworld.com/en/models/1809617",
    },
    {
        number: "23",
        name: "Minecraft",
        image: "./images/23-minecraft.webp",
        url: "https://makerworld.com/en/models/1809711",
    },
    {
        number: "24",
        name: "Hornet",
        image: "./images/24-hornet.webp",
        url: "https://makerworld.com/en/models/1809714",
    },
    {
        number: "25",
        name: "Dory Filled",
        image: "./images/25-dory-filled.webp",
        url: "https://makerworld.com/en/models/1810050",
    },
    {
        number: "26",
        name: "Toothless",
        image: "./images/26-toothless.webp",
        url: "https://makerworld.com/en/models/1810052",
    },
    {
        number: "27",
        name: "Impostor",
        image: "./images/27-impostor.webp",
        url: "https://makerworld.com/en/models/1810158",
    },
    {
        number: "28",
        name: "Koopa",
        image: "./images/28-koopa.webp",
        url: "https://makerworld.com/en/models/1810547",
    },
    {
        number: "29",
        name: "Mike",
        image: "./images/29-mike.webp",
        url: "https://makerworld.com/en/models/1811077",
    },
    {
        number: "30",
        name: "Stitch",
        image: "./images/30-stitch.webp",
        url: "https://makerworld.com/en/models/1812837",
    },
    {
        number: "31",
        name: "Perry",
        image: "./images/31-perry.webp",
        url: "https://makerworld.com/en/models/1812839",
    },
    {
        number: "32",
        name: "Bingo",
        image: "./images/32-bingo.webp",
        url: "https://makerworld.com/en/models/1812844",
    },
    {
        number: "33",
        name: "Happy Taco",
        image: "./images/33-happy-taco.webp",
        url: "https://makerworld.com/en/models/1819674",
    },
    {
        number: "34",
        name: "Parrot",
        image: "./images/34-parrot.webp",
        url: "https://makerworld.com/en/models/1824174",
    },
    {
        number: "35",
        name: "Seahorse",
        image: "./images/35-seahorse.webp",
        url: "https://makerworld.com/en/models/1830131",
    },
    {
        number: "36",
        name: "Patrick",
        image: "./images/36-patrick.webp",
        url: "https://makerworld.com/en/models/1841183",
    },
    {
        number: "37",
        name: "Hello Kitty",
        image: "./images/37-hello-kitty.webp",
        url: "https://makerworld.com/en/models/1842673",
    },
    {
        number: "38",
        name: "Rusty",
        image: "./images/38-rusty.webp",
        url: "https://makerworld.com/en/models/1877819",
    },
    {
        number: "39",
        name: "Bandit",
        image: "./images/39-bandit.webp",
        url: "https://makerworld.com/en/models/1877823",
    },
    {
        number: "40",
        name: "Truck",
        image: "./images/40-truck.webp",
        url: "https://makerworld.com/en/models/1877828",
    },
    {
        number: "41",
        name: "Rocket",
        image: "./images/41-rocket.webp",
        url: "https://makerworld.com/en/models/1882247",
    },
    {
        number: "42",
        name: "Dinosaur",
        image: "./images/42-dinosaur.webp",
        url: "https://makerworld.com/en/models/1882250",
    },
    {
        number: "43",
        name: "Robot",
        image: "./images/43-robot.webp",
        url: "https://makerworld.com/en/models/1882265",
    },
    {
        number: "44",
        name: "Ice Cream",
        image: "./images/44-ice-cream.webp",
        url: "https://makerworld.com/en/models/1884244",
    },
    {
        number: "45",
        name: "Hot Air Balloon",
        image: "./images/45-hot-air-balloon.webp",
        url: "https://makerworld.com/en/models/1884258",
    },
    {
        number: "46",
        name: "Bearded Dragon",
        image: "./images/46-bearded-dragon.webp",
        url: "https://makerworld.com/en/models/2034349",
    },
    {
        number: "47",
        name: "Lil Petey",
        image: "./images/47-lil-petey.webp",
        url: "https://makerworld.com/en/models/2037231",
    },
    {
        number: "48",
        name: "Tigger",
        image: "./images/48-tigger.webp",
        url: "https://makerworld.com/en/models/2038384",
    },
    {
        number: "49",
        name: "Keroppi",
        image: "./images/49-keroppi.webp",
        url: "https://makerworld.com/en/models/2041495",
    },
    {
        number: "50",
        name: "Aang",
        image: "./images/50-aang.webp",
        url: "https://makerworld.com/en/models/2044852",
    },
    {
        number: "51",
        name: "Sonic",
        image: "./images/51-sonic.webp",
        url: "https://makerworld.com/en/models/2048876",
    },
    {
        number: "52",
        name: "Cinnamoroll",
        image: "./images/52-cinnamoroll.webp",
        url: "https://makerworld.com/en/models/2052450",
    },
    {
        number: "53",
        name: "Ninja",
        image: "./images/53-ninja.webp",
        url: "https://makerworld.com/en/models/2152025",
    },
    {
        number: "54",
        name: "Dumbledore",
        image: "./images/54-dumbledore.webp",
        url: "https://makerworld.com/en/models/2152032",
    },
    {
        number: "55",
        name: "Joy",
        image: "./images/55-joy.webp",
        url: "https://makerworld.com/en/models/2154270",
    },
    {
        number: "56",
        name: "Football Player",
        image: "./images/56-football-player.webp",
        url: "https://makerworld.com/en/models/2154378",
    },
    {
        number: "57",
        name: "Yoshi",
        image: "./images/57-yoshi.webp",
        url: "https://makerworld.com/en/models/2157848",
    },
    {
        number: "58",
        name: "Anger",
        image: "./images/58-anger.webp",
        url: "https://makerworld.com/en/models/2158025",
    },
    {
        number: "59",
        name: "Iron Man",
        image: "./images/59-iron-man.webp",
        url: "https://makerworld.com/en/models/2158235",
    },
    {
        number: "60",
        name: "Ori",
        image: "./images/60-ori.webp",
        url: "https://makerworld.com/en/models/2158256",
    },
    {
        number: "61",
        name: "Peach",
        image: "./images/61-peach.webp",
        url: "https://makerworld.com/en/models/2160505",
    },
    {
        number: "62",
        name: "Daniel Tiger",
        image: "./images/62-daniel-tiger.webp",
        url: "https://makerworld.com/en/models/2168602",
    },
    {
        number: "63",
        name: "MerCat",
        image: "./images/63-mercat.webp",
        url: "https://makerworld.com/en/models/2178109",
    },
    {
        number: "64",
        name: "Dobby",
        image: "./images/64-dobby.webp",
        url: "https://makerworld.com/en/models/2183176",
    },
    {
        number: "65",
        name: "Piglet",
        image: "./images/65-piglet.webp",
        url: "https://makerworld.com/en/models/2185067",
    },
    {
        number: "66",
        name: "Flash",
        image: "./images/66-flash.webp",
        url: "https://makerworld.com/en/models/2259394",
    },
    {
        number: "67",
        name: "Bulbasaur",
        image: "./images/67-bulbasaur.webp",
        url: "https://makerworld.com/en/models/2263597",
    },
    {
        number: "68",
        name: "Train",
        image: "./images/68-train.webp",
        url: "https://makerworld.com/en/models/2267898",
    },
    {
        number: "69",
        name: "Kuromi",
        image: "./images/69-kuromi.webp",
        url: "https://makerworld.com/en/models/2273126",
    },
    {
        number: "70",
        name: "Hedgehog",
        image: "./images/70-hedgehog.webp",
        url: "https://makerworld.com/en/models/2277854",
    },
    {
        number: "71",
        name: "Squirtle",
        image: "./images/71-squirtle.webp",
        url: "https://makerworld.com/en/models/2282441",
    },
    {
        number: "72",
        name: "Toad",
        image: "./images/72-toad.webp",
        url: "https://makerworld.com/en/models/2289326",
    },
    {
        number: "73",
        name: "Gru",
        image: "./images/73-gru.webp",
        url: "https://makerworld.com/en/models/2292599",
    },
    {
        number: "74",
        name: "Sadness",
        image: "./images/74-sadness.webp",
        url: "https://makerworld.com/en/models/2305831",
    },
    {
        number: "75",
        name: "Ness",
        image: "./images/75-ness.webp",
        url: "https://makerworld.com/en/models/2310951",
    },
    {
        number: "76",
        name: "Hermione",
        image: "./images/76-hermione.webp",
        url: "https://makerworld.com/en/models/2316884",
    },
    {
        number: "77",
        name: "Puss in Boots",
        image: "./images/77-puss-in-boots.webp",
        url: "https://makerworld.com/en/models/2325200",
    },
    {
        number: "78",
        name: "Charmander",
        image: "./images/78-charmander.webp",
        url: "https://makerworld.com/en/models/2421439",
    },
    {
        number: "79",
        name: "Spongebob",
        image: "./images/79-spongebob.webp",
        url: "https://makerworld.com/en/models/2423308",
    },
    {
        number: "80",
        name: "Snoopy",
        image: "./images/80-snoopy.webp",
        url: "https://makerworld.com/en/models/2423333",
    },
    {
        number: "81",
        name: "Eevee",
        image: "./images/81-eevee.webp",
        url: "https://makerworld.com/en/models/2423561",
    },
    {
        number: "82",
        name: "Mario",
        image: "./images/82-mario.webp",
        url: "https://makerworld.com/en/models/2427721",
    },
    {
        number: "83",
        name: "Gengar",
        image: "./images/83-gengar.webp",
        url: "https://makerworld.com/en/models/2429387",
    },
    {
        number: "84",
        name: "Ron Weasley",
        image: "./images/84-ron-weasley.webp",
        url: "https://makerworld.com/en/models/2432565",
    },
    {
        number: "85",
        name: "Totoro",
        image: "./images/85-totoro.webp",
        url: "https://makerworld.com/en/models/2435694",
    },
    {
        number: "86",
        name: "Goku",
        image: "./images/86-goku.webp",
        url: "https://makerworld.com/en/models/2438821",
    },
    {
        number: "87",
        name: "Einstein",
        image: "./images/87-einstein.webp",
        url: "https://makerworld.com/en/models/2442945",
    },
    {
        number: "88",
        name: "Batman",
        image: "./images/88-batman.webp",
        url: "https://makerworld.com/en/models/2446691",
    },
    {
        number: "89",
        name: "Captain America",
        image: "./images/89-captain-america.webp",
        url: "https://makerworld.com/en/models/2450446",
    },
    {
        number: "90",
        name: "Snorlax",
        image: "./images/90-snorlax.webp",
        url: "https://makerworld.com/en/models/2465065",
    },
    {
        number: "91",
        name: "Eiffel Tower",
        image: "./images/91-eiffel-tower.webp",
        url: "https://makerworld.com/en/models/2470245",
    },
    {
        number: "92",
        name: "Corgi",
        image: "./images/92-corgi.webp",
        url: "https://makerworld.com/en/models/2473681",
    },
    {
        number: "93",
        name: "Cloud",
        image: "./images/93-cloud.webp",
        url: "https://makerworld.com/en/models/2478660",
    },
    {
        number: "94",
        name: "Greg Heffley",
        image: "./images/94-greg-heffley.webp",
        url: "https://makerworld.com/en/models/2482581",
    },
    {
        number: "95",
        name: "Donkey Kong",
        image: "./images/95-donkey-kong.webp",
        url: "https://makerworld.com/en/models/2487402",
    },
    {
        number: "96",
        name: "Chocobo",
        image: "./images/96-chocobo.webp",
        url: "https://makerworld.com/en/models/2491918",
    },
    {
        number: "97",
        name: "Shadow",
        image: "./images/97-shadow.webp",
        url: "https://makerworld.com/en/models/2497535",
    },
    {
        number: "98",
        name: "Goomba",
        image: "./images/98-goomba.webp",
        url: "https://makerworld.com/en/models/2500701",
    },
    {
        number: "99",
        name: "Vivi",
        image: "./images/99-vivi.webp",
        url: "https://makerworld.com/en/models/2505778",
    },
    {
        number: "100",
        name: "Umbreon",
        image: "./images/100-umbreon.webp",
        url: "https://makerworld.com/en/models/2510146",
    },
    {
        number: "101",
        name: "Cuphead",
        image: "./images/101-cuphead.webp",
        url: "https://makerworld.com/en/models/2680792",
    },
    {
        number: "102",
        name: "Anxiety",
        image: "./images/102-anxiety.webp",
        url: "https://makerworld.com/en/models/2683951",
    },
    {
        number: "103",
        name: "Spidey",
        image: "./images/103-spidey.webp",
        url: "https://makerworld.com/en/models/2689115",
    },
    {
        number: "104",
        name: "Dragon",
        image: "./images/104-dragon.webp",
        url: "https://makerworld.com/en/models/2693545",
    },
    {
        number: "105",
        name: "Mimikyu",
        image: "./images/105-mimikyu.webp",
        url: "https://makerworld.com/en/models/2698738",
    },
    {
        number: "106",
        name: "Cat",
        image: "./images/106-cat.webp",
        url: "https://makerworld.com/en/models/2703173",
    },
    {
        number: "107",
        name: "Rocky",
        image: "./images/107-rocky.webp",
        url: "https://makerworld.com/en/models/2712130",
    },
    {
        number: "108",
        name: "Angel",
        image: "./images/108-angel.webp",
        url: "https://makerworld.com/en/models/2717830",
    },
    {
        number: "109",
        name: "Rubber Ducky",
        image: "./images/109-rubber-ducky.webp",
        url: "https://makerworld.com/en/models/2792265",
    },
    {
        number: "110",
        name: "Appa",
        image: "./images/110-appa.webp",
        url: "https://makerworld.com/en/models/2800298",
    },
    {
        number: "111",
        name: "Kakamora",
        image: "./images/111-kakamora.webp",
        url: "https://makerworld.com/en/models/2809124",
    },
    {
        number: "112",
        name: "This is fine",
        image: "./images/112-this-is-fine.webp",
        url: "https://makerworld.com/en/models/2818809",
    },
    {
        number: "113",
        name: "Trogdor",
        image: "./images/113-trogdor.webp",
        url: "https://makerworld.com/en/models/2826281",
    },
    {
        number: "114",
        name: "Shrek",
        image: "./images/114-shrek.webp",
        url: "https://makerworld.com/en/models/2834373",
    },
    {
        number: "115",
        name: "Not Sure If (Fry)",
        image: "./images/115-not-sure-if-_fry_.webp",
        url: "https://makerworld.com/en/models/2842067",
    },
    {
        number: "116",
        name: "Pirate",
        image: "./images/116-pirate.webp",
        url: "https://makerworld.com/en/models/2850972",
    },
    {
        number: "117",
        name: "Bowser",
        image: "./images/117-bowser.webp",
        url: "https://makerworld.com/en/models/2858581",
    },
    {
        number: "118",
        name: "Astronaut",
        image: "./images/118-astronaut.webp",
        url: "https://makerworld.com/en/models/2866989",
    },
    {
        number: "119",
        name: "Twilight Sparkle",
        image: "./images/119-twilight-sparkle.webp",
        url: "https://makerworld.com/en/models/2875677",
    },
    {
        number: "120",
        name: "Homestar Runner",
        image: "./images/120-homestar-runner.webp",
        url: "https://makerworld.com/en/models/2884508",
    },
    {
        number: "121",
        name: "Mr. Incredible",
        image: "./images/121-mr-incredible.webp",
        url: "https://makerworld.com/en/models/2892896",
    },
    {
        number: "122",
        name: "Poodle",
        image: "./images/122-poodle.webp",
        url: "https://makerworld.com/en/models/2901359",
    },
    {
        number: "123",
        name: "Hobbes",
        image: "./images/123-hobbes.webp",
        url: "https://makerworld.com/en/models/2910086",
    },
    {
        number: "124",
        name: "Light",
        image: "./images/124-light.webp",
        url: "https://makerworld.com/en/models/2914806",
    },
    {
        number: "125",
        name: "Harry Potter Full",
        image: "./images/125-harry-potter-full.webp",
        url: "https://makerworld.com/en/models/2918494",
    },
    {
        number: "126",
        name: "Gojo",
        image: "./images/126-gojo.webp",
        url: "https://makerworld.com/en/models/2922896",
    },
    {
        number: "127",
        name: "Bowser Jr.",
        image: "./images/127-bowser-jr.webp",
        url: "https://makerworld.com/en/models/2926841",
    },
    {
        number: "128",
        name: "Lightning McQueen",
        image: "./images/128-lightning-mcqueen.webp",
        url: "https://makerworld.com/en/models/2930816",
    },
    {
        number: "129",
        name: "The Radiance",
        image: "./images/129-the-radiance.webp",
        url: "https://makerworld.com/en/models/2935801",
    },
    {
        number: "130",
        name: "Crash Bandicoot",
        image: "./images/130-crash-bandicoot.webp",
        url: "https://makerworld.com/en/models/2939566",
    },
    {
        number: "131",
        name: "My Melody",
        image: "./images/131-my-melody.webp",
        url: "https://makerworld.com/en/models/2944010",
    },
    {
        number: "132",
        name: "Sandwing",
        image: "./images/132-sandwing.webp",
        url: "https://makerworld.com/en/models/2947710",
    },
    {
        number: "133",
        name: "Arbok",
        image: "./images/133-arbok.webp",
        url: "https://makerworld.com/en/models/2952124",
    },
    {
        number: "134",
        name: "Soccer Player",
        image: "./images/134-soccer-player.webp",
        url: "https://makerworld.com/en/models/2955870",
    },
    {
        number: "135",
        name: "Ryuk",
        image: "./images/135-ryuk.webp",
        url: "https://makerworld.com/en/models/2959528",
    },
    {
        number: "136",
        name: "Squidward",
        image: "./images/136-squidward.webp",
        url: "https://makerworld.com/en/models/2963264",
    },
    {
        number: "137",
        name: "Luma",
        image: "./images/137-luma.webp",
        url: "https://makerworld.com/en/models/2967999",
    },
    {
        number: "138",
        name: "Cookie Monster",
        image: "./images/138-cookie-monster.webp",
        url: "https://makerworld.com/en/models/2971738",
    },
    {
        number: "139",
        name: "Tommy Pickles",
        image: "./images/139-tommy-pickles.webp",
        url: "https://makerworld.com/en/models/2975208",
    },
    {
        number: "140",
        name: "Princess Daisy",
        image: "./images/140-princess-daisy.webp",
        url: "https://makerworld.com/en/models/2979619",
    },
    {
        number: "141",
        name: "Kermit the Frog",
        image: "./images/141-kermit-the-frog.webp",
        url: "https://makerworld.com/en/models/2982701",
    },
    {
        number: "142",
        name: "Wednesday",
        image: "./images/142-wednesday.webp",
        url: "https://makerworld.com/en/models/2986752",
    },
    {
        number: "143",
        name: "Togepi",
        image: "./images/143-togepi.webp",
        url: "https://makerworld.com/en/models/2991163",
    },
    {
        number: "144",
        name: "World Cup Trophy",
        image: "./images/144-world-cup-trophy.webp",
        url: "https://makerworld.com/en/models/2999138",
    },
    {
        number: "145",
        name: "Schroeder",
        image: "./images/145-schroeder.webp",
        url: "https://makerworld.com/en/models/3002898",
    },
    {
        number: "146",
        name: "Dexter",
        image: "./images/146-dexter.webp",
        url: "https://makerworld.com/en/models/3006682",
    },
    {
        number: "147",
        name: "Rainbow Dash",
        image: "./images/147-rainbow-dash.webp",
        url: "https://makerworld.com/en/models/3011052",
    },
    {
        number: "148",
        name: "Eleven",
        image: "./images/148-eleven.webp",
        url: "https://makerworld.com/en/models/3015090",
    },
    {
        number: "149",
        name: "Chilli",
        image: "./images/149-chilli.webp",
        url: "https://makerworld.com/en/models/3019135",
    },
    {
        number: "150",
        name: "Shy Guy",
        image: "./images/150-shy-guy.webp",
        url: "https://makerworld.com/en/models/3022933",
    },
    {
        number: "151",
        name: "Phineas Flynn",
        image: "./images/151-phineas-flynn.webp",
        url: "https://makerworld.com/en/models/3027217",
    },
    {
        number: "152",
        name: "Dratini",
        image: "./images/152-dratini.webp",
        url: "https://makerworld.com/en/models/3031424",
    },
    {
        number: "153",
        name: "Princess Donut",
        image: "./images/153-princess-donut.webp",
        url: "https://makerworld.com/en/models/3034784",
    },
    {
        number: "154",
        name: "Garfield",
        image: "./images/154-garfield.webp",
        url: "https://makerworld.com/en/models/3038743",
    },
    {
        number: "155",
        name: "Thor",
        image: "./images/155-thor.webp",
        url: "https://makerworld.com/en/models/3042255",
    },
    {
        number: "156",
        name: "Llama",
        image: "./images/156-llama.webp",
        url: "https://makerworld.com/en/models/3046429",
    },
];
